services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amaris-go-app
    ports:
      - "8080:8080"
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=database
      - PGPORT=5432
      - PGDATABASE=${PGDATABASE}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  database:
    image: postgres:latest
    container_name: amaris-postgres-db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network: